name: task_2
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.6
  firebase_auth: ^5.3.3
  firebase_core: ^3.8.0
  firebase_database: ^11.1.6
  image_picker: ^1.1.2
  google_fonts: ^6.2.1
  image: ^4.5.4
  before_after: ^3.2.0
  lottie: ^3.1.3
  permission_handler: ^11.3.1
  saver_gallery: ^4.0.1
  flutter_image_compress: ^2.3.0
  cloud_firestore: ^5.5.1
  http_parser: ^4.0.2
  path: ^1.9.0
  path_provider: ^2.1.5
  shared_preferences: ^2.3.3
  onnxruntime: ^1.4.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/models/
